label: "llama3-8b"
name_or_path: "bartowski/Meta-Llama-3-8B-Instruct-GGUF"
backend_type: "openai_compatible"
api_base_url: "http://localhost:8000"
api_model: "llama-3-8b"
max_new_tokens: 8192
temperature: 0.0
